# IMPORTANT! - DO NOT UNDER ANY CIRCUMSTANCE PUSH THIS FILE TO GITHUB OR OTHER SOURCE CONTROL PLATFORM
google_api_credentials: <GOOGLE_API_CREDENTIALS>
spreadsheet_id_ntl: <SPREADSHEET_ID>
# IMPORTANT! - DO NOT UNDER ANY CIRCUMSTANCE PUSH THIS FILE TO GITHUB OR OTHER SOURCE CONTROL PLATFORM
